name: Production Build & Push Docker Image to DockerHub

on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - ".github/**"
  pull_request:
    branches:
      - master
    # paths-ignore:
    #   - ".github/**"
  # push:
  #   branches: [ "main", "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"

  deploy:
    name: Deploy my app
    runs-on: ubuntu-latest

    permissions:
      deployments: write
    
    steps:
      - uses: actions/checkout@v4

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
        #   environment-url: http://my-app-url.com
          environment: production


# https://support.atlassian.com/jira-cloud-administration/docs/link-github-workflows-and-deployments-to-jira-issues/